version: "3.9"

services:
  bot:
    build: .
    container_name: video-downloader-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./downloads:/app/downloads
